# Generated by Django 4.2.7 on 2026-05-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('featured_image', models.ImageField(help_text='Primary image representing the post.', upload_to='blogs/')),
                ('content', models.TextField(help_text='Markdown or HTML content of the article.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('logo_image', models.ImageField(help_text='Company brand logo (preferably vector/transparent background).', upload_to='clients/')),
                ('website_url', models.URLField(blank=True, help_text='Optional external link to client webpage.', null=True)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order_number', models.IntegerField(default=0, help_text='Order index for sequencing accordion blocks.')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('short_description', models.TextField(help_text='Brief summary shown on grids or previews.')),
                ('full_description', models.TextField(help_text='Detailed case study contents.')),
                ('thumbnail_image', models.ImageField(help_text='High-resolution thumbnail image.', upload_to='projects/')),
                ('category', models.CharField(help_text='e.g. Web App, UI/UX Design, Branding', max_length=100)),
                ('technologies', models.CharField(help_text='Comma-separated technologies (e.g. Next.js, TailwindCSS, Django)', max_length=500)),
                ('featured', models.BooleanField(default=False, help_text='If True, this project highlights in home portfolios.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_image', models.ImageField(blank=True, help_text='Optional custom graphic representing this service.', null=True, upload_to='services/')),
                ('icon_name', models.CharField(blank=True, help_text='Lucide-react icon identifier (e.g. Search, Layout, Code2).', max_length=100)),
                ('order_number', models.IntegerField(default=0, help_text='Order index for sequencing on the frontpage.')),
            ],
            options={
                'ordering': ['order_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Metric label, e.g. 'Projects Shipped'", max_length=100)),
                ('value', models.IntegerField(help_text='Numerical counter value.')),
                ('suffix', models.CharField(default='+', help_text="Appended text (e.g., '+', '%', '/7').", max_length=20)),
            ],
        ),
    ]
